### ISSUE TITLE
Create skeleton of TestNG based test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-security-client10#1]

**Comment by dstenger** [comment]
CITE Maven archetype [1] is used for generation of first structure:

```
mvn archetype:generate -B \
    -DarchetypeGroupId=org.opengis.cite \
    -DarchetypeArtifactId=ets-archetype-testng \
    -DarchetypeVersion=2.7-SNAPSHOT \
    -Dets-code=security-client10 \
    -DartifactId=ets-security-client10 \
    -Dpackage=org.opengis.cite.securityclient10
```

Create initial commit:

```
git init
git add .
git commit -m"Create skeleton of TestNG based test suite with CITE Maven archetype"
git remote add origin git@github.com:opengeospatial/ets-security-client10.git
git push -u origin master
```

Commit: https://github.com/opengeospatial/ets-security-client10/commit/1a948974fa060a403c87801420c446723ec26ddf

[1] https://github.com/opengeospatial/ets-archetype-testng

**Comment by dstenger** [comment]
## Further adjustments

Add gitignore: https://github.com/opengeospatial/ets-security-client10/commit/a44bb0530b31391ba6fefc7b6e2b31176d06bde3
Update ets-common version: https://github.com/opengeospatial/ets-security-client10/commit/587cd6073ceb704e45b95a30a8e87da315aae3b0
Remove method assertSchematronValid: https://github.com/opengeospatial/ets-security-client10/commit/03f7804127770ec004a33e6267b8078fa68a006d
Move resources to correct package and update paths: https://github.com/opengeospatial/ets-security-client10/commit/c0227fc37d4d32d99c01a83d83a5e5280be4aa9e

**Comment by lgoltz** [comment]
Skeleton of the test suite was created. `mvn clean install` was successful.
